services:
  - type: web
    name: voyara-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://voyara-h7fj.vercel.app
      - key: DATABASE_NAME
        value: voyara
